Try to fix ufunc casting error in _anglesToVector by using the math module instead of numpy.
Error: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'